// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-_pl9KEk77zKRjuKuetP-Bl7GjwEG5hA',
    appId: '1:1010129248621:web:baf1ac901780bcda47fa64',
    messagingSenderId: '1010129248621',
    projectId: 'firstapp-d1b45',
    authDomain: 'firstapp-d1b45.firebaseapp.com',
    storageBucket: 'firstapp-d1b45.firebasestorage.app',
    measurementId: 'G-WNHBX0K2NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7GsceqHamSojS71tQg533B4napbhhx2Y',
    appId: '1:1010129248621:android:c2422ea012efafc447fa64',
    messagingSenderId: '1010129248621',
    projectId: 'firstapp-d1b45',
    storageBucket: 'firstapp-d1b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASRwtCHnJokFFzXvysicgVjIs5iNlDoOI',
    appId: '1:1010129248621:ios:e7654ddc2bb1733847fa64',
    messagingSenderId: '1010129248621',
    projectId: 'firstapp-d1b45',
    storageBucket: 'firstapp-d1b45.firebasestorage.app',
    iosBundleId: 'com.example.mobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASRwtCHnJokFFzXvysicgVjIs5iNlDoOI',
    appId: '1:1010129248621:ios:e7654ddc2bb1733847fa64',
    messagingSenderId: '1010129248621',
    projectId: 'firstapp-d1b45',
    storageBucket: 'firstapp-d1b45.firebasestorage.app',
    iosBundleId: 'com.example.mobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-_pl9KEk77zKRjuKuetP-Bl7GjwEG5hA',
    appId: '1:1010129248621:web:1798b9ad8c5798a747fa64',
    messagingSenderId: '1010129248621',
    projectId: 'firstapp-d1b45',
    authDomain: 'firstapp-d1b45.firebaseapp.com',
    storageBucket: 'firstapp-d1b45.firebasestorage.app',
    measurementId: 'G-SZ4KBBX9VX',
  );
}
